export default [
    {
        id: 1,
        name: 'Buttermilk Pineapple Carrot Cake',
        ingredients: ['butter', 'sugar', 'buttermilk', 'egg', 'vanilla', 'flour', 'baking soda', 'salt', 'carrot', 'pineapple', 'walnut'],
        href: 'https://tasty.recipes/buttermilk-pineapple-carrot-cake/',
        image: 'https://tasty.recipes/wp-content/uploads/2019/02/76AEAAD2-B719-4FDA-BB1C-564462638DF6.jpeg',
    },
    {
        id: 2,
        name: 'Low-Sugar Apple Tart',
        ingredients: [
            'rolled oats',
            'butter',
            'flour',
            'baking soda',
            'salt',
            'water',
            'apple',
            'lemon',
            'cinnamon',
            'nutmeg',
            'applesauce ',
            'apricot jam',
        ],
        href: 'https://tasty.recipes/low-sugar-apple-tart/',
        image: 'https://tasty.recipes/wp-content/uploads/2019/01/201317.jpg',
    },
    {
        id: 3,
        name: 'Fajita Chicken And Rice Dinner',
        ingredients: [
            'olive oil',
            'lime',
            'agave',
            'salt',
            'oregano',
            'chili',
            'cumin',
            'chicken',
            'onion',
            'bell pepper',
            'rice',
            'chicken stock',
            'black pepper',
            'cilantro',
        ],
        href: 'https://tasty.recipes/fajita-chicken-rice-dinner/',
        image: 'https://tasty.recipes/wp-content/uploads/2019/01/202405.jpg',
    },
    {
        id: 4,
        name: 'Chili-cheese Garlic Bread Rolls',
        ingredients: [
            'onion',
            'garlic',
            'beef',
            'salt',
            'pepper',
            'tomato sauce',
            'oregano',
            'cumin',
            'chili',
            'kidney bean',
            'butter',
            'parsley',
            'parmesan',
            'dinner rolls',
            'cheddar',
            'sour cream',
            'green onion',
        ],
        href: 'https://tasty.recipes/garlic-bread-rolls/',
        image: 'https://tasty.recipes/wp-content/uploads/2018/12/Chili-cheese-Garlic-Bread-Rolls.jpg',
    },
    {
        id: 5,
        name: 'Chicken Alfredo Ravioli Lasagna',
        ingredients: [
            'butter',
            'garlic',
            'heavy cream',
            'parmesan',
            'salt',
            'pepper',
            'nutmeg',
            'spinach ricotta ravioli',
            'chicken',
            'mozzarella',
            'parsley',
        ],
        href: 'https://tasty.recipes/chicken-alfredo-ravioli-lasagna/',
        image: 'https://tasty.recipes/wp-content/uploads/2018/09/Chicken-Alfredo-Ravioli-Lasagna.jpg',
    },
    {
        id: 6,
        name: 'Buttermilk Pineapple Carrot Cake',
        ingredients: ['butter', 'sugar', 'buttermilk', 'egg', 'vanilla', 'flour', 'baking soda', 'salt', 'carrot', 'pineapple', 'walnut'],
        href: 'https://tasty.recipes/buttermilk-pineapple-carrot-cake/',
        image: 'https://tasty.recipes/wp-content/uploads/2019/02/76AEAAD2-B719-4FDA-BB1C-564462638DF6.jpeg',
    },
    {
        id: 7,
        name: 'Low-Sugar Apple Tart',
        ingredients: [
            'rolled oats',
            'butter',
            'flour',
            'baking soda',
            'salt',
            'water',
            'apple',
            'lemon',
            'cinnamon',
            'nutmeg',
            'applesauce ',
            'apricot jam',
        ],
        href: 'https://tasty.recipes/low-sugar-apple-tart/',
        image: 'https://tasty.recipes/wp-content/uploads/2019/01/201317.jpg',
    },
    {
        id: 8,
        name: 'Fajita Chicken And Rice Dinner',
        ingredients: [
            'olive oil',
            'lime',
            'agave',
            'salt',
            'oregano',
            'chili',
            'cumin',
            'chicken',
            'onion',
            'bell pepper',
            'rice',
            'chicken stock',
            'black pepper',
            'cilantro',
        ],
        href: 'https://tasty.recipes/fajita-chicken-rice-dinner/',
        image: 'https://tasty.recipes/wp-content/uploads/2019/01/202405.jpg',
    },
    {
        id: 9,
        name: 'Chili-cheese Garlic Bread Rolls',
        ingredients: [
            'onion',
            'garlic',
            'beef',
            'salt',
            'pepper',
            'tomato sauce',
            'oregano',
            'cumin',
            'chili',
            'kidney bean',
            'butter',
            'parsley',
            'parmesan',
            'dinner rolls',
            'cheddar',
            'sour cream',
            'green onion',
        ],
        href: 'https://tasty.recipes/garlic-bread-rolls/',
        image: 'https://tasty.recipes/wp-content/uploads/2018/12/Chili-cheese-Garlic-Bread-Rolls.jpg',
    },
    {
        id: 10,
        name: 'Chicken Alfredo Ravioli Lasagna',
        ingredients: [
            'butter',
            'garlic',
            'heavy cream',
            'parmesan',
            'salt',
            'pepper',
            'nutmeg',
            'spinach ricotta ravioli',
            'chicken',
            'mozzarella',
            'parsley',
        ],
        href: 'https://tasty.recipes/chicken-alfredo-ravioli-lasagna/',
        image: 'https://tasty.recipes/wp-content/uploads/2018/09/Chicken-Alfredo-Ravioli-Lasagna.jpg',
    },
];
